### ISSUE TITLE
What algorithm is the package?

### ISSUE THREAD

**Issue by hscspring** [zhcHoward/Kmap#2]
hello, i didn't see the algorithm in your README, i was wondering if you can tell me~~  
thank you~~

**Comment by zhcHoward** [comment]
Sorry for replying late, I didn't check the notification recently.
There is an algorithm in the wiki page (linked in the README), it is an efficient algorithm. But I didn't figure out how to implement it. My algorithm is simply:
1. Simplify terms two by two from the original list
2. Generate a new list of terms
3. Remove repeated terms in the new list
4. Add the terms that can't be simplified from original list to new terms for next loop, if there is any
5. Redo step 1, until no terms can be simplified
6. In the latest list of terms, remove the terms that don't have unique sources
